language: ruby
rvm:
  - 2
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - JEKYLL_VERSION=2.1.0
    - JEKYLL_VERSION=2.0
    - JEKYLL_VERSION=3.0.0.pre.beta7
before_script:
  - bundle exec jekyll --version
script:
  - bundle exec rake test
  - bundle exec rake site:test
notifications:
  email: false
